name: Build GitHub Pages from Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install pdocs
        run: pip install pdocs

      - name: Generate HTML pages
        run: pdoc --html pyhockey
    
      - uses: actions/upload-pages-artifact@v4
        with:
          path: html/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
